name: transportation
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.1
  path: any
  shared_preferences: ^2.5.3
  crypto: ^3.0.3
  http: ^1.4.0
  flutter_svg: ^2.2.0
  url_launcher: ^6.3.2
  google_sign_in: 6.3.0
  google_maps_flutter: ^2.5.0
  flutter_stripe: ^11.5.0
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/temp/
    - assets/svg/
